# Generated by Django 2.2.7 on 2020-03-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creationDate', models.DateField(auto_now_add=True, null=True)),
                ('numberOfEntities', models.IntegerField(default=0, editable=False)),
                ('logo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='1', max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastTicket', models.DateTimeField(editable=False, null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='1', max_length=200)),
                ('scanned', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('numberOfOngoingTickets', models.IntegerField(default=0)),
                ('hoursBetweenTickets', models.IntegerField(default=1)),
                ('shouldHaveTextBox', models.BooleanField(default=False)),
                ('shouldHaveInfoBox', models.BooleanField(default=False)),
                ('infoBoxContent', models.CharField(default='-', max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iisy_landing.Department')),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('uuid', models.CharField(default='1', max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iisy_landing.Department')),
                ('types', models.ManyToManyField(to='iisy_landing.EntityType')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRoom', models.BooleanField(default=False)),
                ('entity_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='1', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Unresolved'), ('2', 'Ongoing'), ('3', 'Dismissed'), ('4', 'Done')], default='1', max_length=10)),
                ('message', models.CharField(max_length=400)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iisy_landing.Department')),
                ('entity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iisy_landing.Entity')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iisy_landing.Room')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='entityType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iisy_landing.EntityType'),
        ),
    ]
