# Generated by Django 2.2.7 on 2020-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisy_landing', '0003_room_lastticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hoursBetweenTickets',
            field=models.IntegerField(default=1),
        ),
    ]
