# Generated by Django 2.2.7 on 2020-03-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iisy_landing', '0004_room_hoursbetweentickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='entity_name',
        ),
    ]
