# Generated by Django 2.2.7 on 2020-03-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisy_landing', '0005_remove_ticket_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
