# Generated by Django 2.2.7 on 2020-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisy_landing', '0006_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='infoBoxContent',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
