# Generated by Django 2.2.7 on 2020-03-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iisy_landing', '0007_auto_20200312_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entityType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iisy_landing.EntityType'),
        ),
    ]
